# Generated by Django 4.1.3 on 2022-11-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comerce', '0003_productos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
