# Generated by Django 4.1.3 on 2022-12-02 03:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comerce', '0004_alter_productos_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 12, 2, 0, 2, 53, 508122), verbose_name='Fecha'),
        ),
    ]
