# Generated by Django 4.1.3 on 2022-12-02 04:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comerce', '0005_alter_ventas_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='permiso',
        ),
        migrations.AlterField(
            model_name='productos',
            name='nombre_producto',
            field=models.CharField(max_length=200, verbose_name='Nombre_Producto'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 12, 2, 1, 53, 16, 92921), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Permisos',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
