# Generated by Django 4.1.3 on 2022-12-02 04:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comerce', '0006_remove_usuarios_permiso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 12, 2, 1, 53, 41, 989784), verbose_name='Fecha'),
        ),
    ]
