# Generated by Django 4.1.3 on 2022-12-02 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comerce', '0007_alter_ventas_fecha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ventas',
        ),
    ]
