# Generated by Django 4.1.3 on 2022-12-02 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comerce', '0002_ventas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='fecha',
            field=models.DateField(default=datetime.datetime(2022, 12, 2, 2, 14, 37, 664027), verbose_name='Fecha'),
        ),
    ]
