# Generated by Django 4.1.3 on 2022-12-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comerce', '0003_alter_ventas_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventas',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
    ]
