# Generated by Django 4.1.2 on 2022-11-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100, verbose_name='Usuario')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('producto', models.CharField(max_length=100, verbose_name='Usuario')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('monto', models.FloatField(verbose_name='Monto')),
            ],
        ),
    ]
