# Generated by Django 4.1.3 on 2022-12-11 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='baja',
            field=models.BooleanField(default=False, verbose_name='Baja'),
        ),
        migrations.AddField(
            model_name='ventas',
            name='baja',
            field=models.BooleanField(default=False, verbose_name='Baja'),
        ),
    ]
