# Generated by Django 4.1.3 on 2022-11-22 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comerce', '0002_categorias_permisos_productos_usuarios_ventas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='imagen',
            field=models.ImageField(default='', upload_to='static/images/'),
            preserve_default=False,
        ),
    ]
